from pydantic import BaseModel, Field
from typing import List

# ==============================================================================
# 1. Shared / Common Schemas
# ==============================================================================

# ==============================================================================
# 2. Crowd Intelligence Schemas
# ==============================================================================

class BottleneckZone(BaseModel):
    zone_id: str = Field(description="Unique ID of the bottleneck stadium zone")
    density_index: float = Field(description="Density of people per square meter (0.0 to 10.0)")
    status: str = Field(description="Visual threat categorization: Stable, Warning, Critical")
    flow_rate: str = Field(description="Pacing estimation: e.g. '15 people/min'")

class CrowdAnalysisResult(BaseModel):
    overall_risk_level: str = Field(description="Overall crowd threat level: Green, Yellow, Red")
    crowd_density_score: float = Field(description="Aggregated stadium-wide density average (0.0 to 10.0)")
    active_bottlenecks: List[BottleneckZone] = Field(default_factory=list)
    system_alerts: List[str] = Field(default_factory=list, description="Immediate warnings generated by AI")
    tactical_recommendations: List[str] = Field(default_factory=list, description="Safety operator action advice")
    # Explainable AI fields
    reason: str = Field(description="Why this overall risk level and set of recommendations was issued")
    confidence_score: float = Field(description="Confidence percentage of the safety risk analysis (0 to 100)")
    expected_impact: str = Field(description="Predicted impact on crowd dispersion and flow safety if implemented")
    alternative_recommendation: str = Field(description="Secondary strategy if primary route/action is blocked")


# ==============================================================================
# 3. Accessibility Hub Schemas
# ==============================================================================

class AccessibilityStep(BaseModel):
    instruction: str = Field(description="Visual or directional instruction text")
    is_step_free: bool = Field(description="Whether this segment is completely step-free/wheelchair compliant")
    sensory_rating: str = Field(description="Acoustics & sensory category: Loud, Moderate, Quiet")

class AccessibilityRouteResult(BaseModel):
    service_requested: str = Field(description="Type of program: Wheelchair, Vision, Hearing, Senior, Children")
    route_narration: str = Field(description="Descriptive speech-ready text for screen readers and voice aids")
    navigation_steps: List[AccessibilityStep] = Field(default_factory=list)
    nearby_ada_amenities: List[str] = Field(default_factory=list, description="ADA restrooms, tactile pads along the path")
    companion_team_notified: bool = Field(description="Whether a physical helper was dispatched automatically")
    # Explainable AI fields
    reason: str = Field(description="Why this specific accessible path or dispatch action was chosen")
    confidence_score: float = Field(description="Confidence percentage of the routing engine (0 to 100)")
    expected_impact: str = Field(description="Expected physical relief and accessibility optimization score")
    alternative_recommendation: str = Field(description="Alternative step-free pathway if primary elevators or corridors are congested")


# ==============================================================================
# 4. Transport Nexus Schemas
# ==============================================================================

class TransitOption(BaseModel):
    mode: str = Field(description="Transit mechanism: Metro, Shuttle Bus, Rideshare, Walking, Taxi")
    estimated_duration_mins: int = Field(description="Estimated travel duration in minutes")
    estimated_cost_usd: float = Field(description="Cost index in USD")
    congestion_level: str = Field(description="Delay status: Low, Medium, High")
    carbon_footprint_kg: float = Field(description="Co2 equivalent emitted in kilograms")

class TransportnexusResult(BaseModel):
    origin_sector: str = Field(description="Fan's starting stadium seating sector")
    target_destination: str = Field(description="Target destination zone or hub")
    recommended_option_mode: str = Field(description="The optimal chosen mode: e.g. Metro")
    travel_time_summary: str = Field(description="Quick natural summary of travel pacing")
    all_transit_options: List[TransitOption] = Field(default_factory=list)
    operator_guideline: str = Field(description="Transit control instructions to optimize disperse paths")
    # Explainable AI fields
    reason: str = Field(description="Why this transit mode is recommended over alternatives")
    confidence_score: float = Field(description="Confidence percentage in travel time and route optimization (0 to 100)")
    expected_impact: str = Field(description="Expected travel time reduction and eco-benefit if followed")
    alternative_recommendation: str = Field(description="Alternative transport option if the primary is delayed or full")


# ==============================================================================
# 5. Sustainability Monitor Schemas
# ==============================================================================

class EcoChallenge(BaseModel):
    challenge_title: str = Field(description="Gamified task for the fans")
    points_reward: int = Field(description="Gamification points rewarded")
    instructions: str = Field(description="Step-by-step instructions for fans")

class SustainabilityResult(BaseModel):
    grid_power_status: str = Field(description="Power consumption categorization: Optimal, Loaded, Critical Peak")
    carbon_offset_percentage: float = Field(description="Current match green offset percentage")
    recycling_compliance_score: int = Field(description="Recycling and sorting rate score (1 to 100)")
    operator_grid_insight: str = Field(description="Actionable HVAC/grid power savings recommendation")
    fan_challenges: List[EcoChallenge] = Field(default_factory=list)
    # Explainable AI fields
    reason: str = Field(description="Why this grid setting and gamification strategy is selected")
    confidence_score: float = Field(description="Confidence percentage of the energy load balancer (0 to 100)")
    expected_impact: str = Field(description="Expected carbon offset or peak load reduction")
    alternative_recommendation: str = Field(description="Fallback grid optimization in case solar or main battery drops")


# ==============================================================================
# 6. Operations Command Schemas
# ==============================================================================

class OperationsCommandResult(BaseModel):
    incident_id: str = Field(description="Unique code identifying the emergency log")
    classification_category: str = Field(description="Incident type: Medical, Security, Structural, Facility")
    priority_level: str = Field(description="Priority rating: Critical, High, Medium, Low")
    closest_volunteer_sector: str = Field(description="Assigned responder sector reference: e.g. Sector 114")
    dispatch_action_code: str = Field(description="Official dispatch code: e.g. CODE-RED-MEDICA")
    incident_response_playbook: str = Field(description="Immediate step-by-step actions for field volunteers")
    shift_crew_briefing_bulletins: List[str] = Field(default_factory=list, description="Shift highlights for brief generator")
    
    # Real-Time Triage Enhancements
    impact_assessment: str = Field(description="Estimated impact of the incident on stadium security, fans, or match schedule")
    suggested_response: str = Field(description="AI recommended tactical playbook response")
    nearest_volunteers_quadrant: str = Field(description="Quadrant ID where closest unassigned volunteers are on standby")
    medical_team_dispatch: str = Field(description="Status of emergency medical dispatcher allocation")
    estimated_resolution_time: str = Field(description="Estimated time to resolve the situation, e.g., '12 minutes'")
    
    # Explainable AI fields
    reason: str = Field(description="Why this severity, category, and dispatch action was calculated")
    confidence_score: float = Field(description="Confidence percentage of the security risk engine (0 to 100)")
    expected_impact: str = Field(description="Expected resolution safety gain if dispatch is followed immediately")
    alternative_recommendation: str = Field(description="Secondary action protocol if primary responders are blocked or delayed")
