from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

# ==============================================================================
# 2. Crowd Intelligence Schemas
# ==============================================================================

class BottleneckZone(BaseModel):
    zone_id: str = Field(description="Unique ID of the bottleneck stadium zone")
    density_index: float = Field(description="Density of people per square meter (0.0 to 10.0)")
    status: str = Field(description="Visual threat categorization: Stable, Warning, Critical")
    flow_rate: str = Field(description="Pacing estimation: e.g. '15 people/min'")

class CrowdAnalysisResult(BaseModel):
    overall_risk_level: str = Field(description="Overall crowd threat level: Green, Yellow, Red")
    crowd_density_score: float = Field(description="Aggregated stadium-wide density average (0.0 to 10.0)")
    active_bottlenecks: List[BottleneckZone] = Field(default_factory=list)
    system_alerts: List[str] = Field(default_factory=list, description="Immediate warnings generated by AI")
    tactical_recommendations: List[str] = Field(default_factory=list, description="Safety operator action advice")


# ==============================================================================
# 3. Accessibility Hub Schemas
# ==============================================================================

class AccessibilityStep(BaseModel):
    instruction: str = Field(description="Visual or directional instruction text")
    is_step_free: bool = Field(description="Whether this segment is completely step-free/wheelchair compliant")
    sensory_rating: str = Field(description="Acoustics & sensory category: Loud, Moderate, Quiet")

class AccessibilityRouteResult(BaseModel):
    service_requested: str
    route_narration: str = Field(description="Descriptive speech-ready text for screen readers and voice aids")
    navigation_steps: List[AccessibilityStep] = Field(default_factory=list)
    nearby_ada_amenities: List[str] = Field(default_factory=list, description="ADA restrooms, tactile pads along the path")
    companion_team_notified: bool = Field(description="Whether a physical helper was dispatched automatically")


# ==============================================================================
# 4. Transport Nexus Schemas
# ==============================================================================

class TransitOption(BaseModel):
    mode: str = Field(description="Transit mechanism: Metro, Shuttle Bus, Rideshare, Walking")
    estimated_duration_mins: int = Field(description="Estimated travel duration in minutes")
    estimated_cost_usd: float = Field(description="Cost index in USD")
    congestion_level: str = Field(description="Delay status: Low, Medium, High")
    carbon_footprint_kg: float = Field(description="Co2 equivalent emitted in kilograms")

class TransportnexusResult(BaseModel):
    origin_sector: str
    target_destination: str
    recommended_option_mode: str = Field(description="The optimal chosen mode: e.g. Metro")
    travel_time_summary: str = Field(description="Quick natural summary of travel pacing")
    all_transit_options: List[TransitOption] = Field(default_factory=list)
    operator_guideline: str = Field(description="Transit control instructions to optimize disperse paths")


# ==============================================================================
# 5. Sustainability Monitor Schemas
# ==============================================================================

class EcoChallenge(BaseModel):
    challenge_title: str
    points_reward: int
    instructions: str

class SustainabilityResult(BaseModel):
    grid_power_status: str = Field(description="Power consumption categorization: Optimal, Loaded, Critical Peak")
    carbon_offset_percentage: float = Field(description="Current match green offset percentage")
    recycling_compliance_score: int = Field(description="Recycling and sorting rate score (1 to 100)")
    operator_grid_insight: str = Field(description="Actionable HVAC/grid power savings recommendation")
    fan_challenges: List[EcoChallenge] = Field(default_factory=list)


# ==============================================================================
# 6. Operations Command Schemas
# ==============================================================================

class OperationsCommandResult(BaseModel):
    incident_id: str
    classification_category: str = Field(description="Incident type: Medical, Security, Structural, Facility")
    priority_level: str = Field(description="Priority rating: Critical, High, Medium, Low")
    closest_volunteer_sector: str = Field(description="Assigned responder sector reference: e.g. Sector 114")
    dispatch_action_code: str = Field(description="Official dispatch code: e.g. CODE-RED-MEDICA")
    incident_response_playbook: str = Field(description="Immediate step-by-step actions for field volunteers")
    shift_crew_briefing_bulletins: List[str] = Field(default_factory=list, description="Shift highlights for brief generator")
